# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'TimeSprit' do
    pod 'CVCalendar', '~> 1.4.0'
end

target 'TimeSpritTests' do

end

target 'TimeSpritUITests' do

end

